import type { Tile } from "./types";

export const base_tiles: Tile[] = [
  {
    id: 19,
    edges: {
      2: { is_blocked: false, neighbor_id: 14 },
      3: { is_blocked: false, neighbor_id: 14 },
      4: { is_blocked: false, neighbor_id: 18 },
      5: { is_blocked: false, neighbor_id: 18 },
      6: { is_blocked: false, neighbor_id: 15 },
      7: { is_blocked: false, neighbor_id: 15 },
      8: { is_blocked: false, neighbor_id: 17 },
      9: { is_blocked: false, neighbor_id: 17 },
      10: { is_blocked: false, neighbor_id: 16 },
      11: { is_blocked: false, neighbor_id: 16 },
      12: { is_blocked: false, neighbor_id: 1 },
    },
  },
  {
    id: 18,
    edges: {
      2: { is_blocked: false, neighbor_id: 9 },
      3: { is_blocked: false, neighbor_id: 9 },
      4: { is_blocked: false, neighbor_id: 16 },
      5: { is_blocked: false, neighbor_id: 16 },
      6: { is_blocked: false, neighbor_id: 13 },
      7: { is_blocked: false, neighbor_id: 13 },
      8: { is_blocked: false, neighbor_id: 15 },
      9: { is_blocked: false, neighbor_id: 15 },
      10: { is_blocked: false, neighbor_id: 19 },
      11: { is_blocked: false, neighbor_id: 19 },
      12: { is_blocked: false, neighbor_id: 3 },
    },
  },
  {
    id: 17,
    edges: {
      2: { is_blocked: false, neighbor_id: 19 },
      3: { is_blocked: false, neighbor_id: 19 },
      4: { is_blocked: false, neighbor_id: 15 },
      5: { is_blocked: false, neighbor_id: 15 },
      6: { is_blocked: false, neighbor_id: 12 },
      7: { is_blocked: false, neighbor_id: 12 },
      8: { is_blocked: false, neighbor_id: 14 },
      9: { is_blocked: false, neighbor_id: 14 },
      10: { is_blocked: false, neighbor_id: 11 },
      11: { is_blocked: false, neighbor_id: 11 },
      12: { is_blocked: false, neighbor_id: 2 },
    },
  },
  {
    id: 16,
    edges: {
      2: { is_blocked: false, neighbor_id: 4 },
      3: { is_blocked: false, neighbor_id: 4 },
      4: { is_blocked: false, neighbor_id: 19 },
      5: { is_blocked: false, neighbor_id: 19 },
      6: { is_blocked: false, neighbor_id: 11 },
      7: { is_blocked: false, neighbor_id: 11 },
      8: { is_blocked: false, neighbor_id: 13 },
      9: { is_blocked: false, neighbor_id: 13 },
      10: { is_blocked: false, neighbor_id: 18 },
      11: { is_blocked: false, neighbor_id: 18 },
      12: { is_blocked: false, neighbor_id: 6 },
    },
  },
  {
    id: 15,
    edges: {
      2: { is_blocked: false, neighbor_id: 18 },
      3: { is_blocked: false, neighbor_id: 18 },
      4: { is_blocked: false, neighbor_id: 13 },
      5: { is_blocked: false, neighbor_id: 13 },
      6: { is_blocked: false, neighbor_id: 10 },
      7: { is_blocked: false, neighbor_id: 10 },
      8: { is_blocked: false, neighbor_id: 12 },
      9: { is_blocked: false, neighbor_id: 12 },
      10: { is_blocked: false, neighbor_id: 17 },
      11: { is_blocked: false, neighbor_id: 17 },
      12: { is_blocked: false, neighbor_id: 19 },
    },
  },
  {
    id: 14,
    edges: {
      2: { is_blocked: false, neighbor_id: 17 },
      3: { is_blocked: false, neighbor_id: 17 },
      4: { is_blocked: false, neighbor_id: 12 },
      5: { is_blocked: false, neighbor_id: 12 },
      6: { is_blocked: false, neighbor_id: 9 },
      7: { is_blocked: false, neighbor_id: 9 },
      8: { is_blocked: false, neighbor_id: 19 },
      9: { is_blocked: false, neighbor_id: 19 },
      10: { is_blocked: false, neighbor_id: 6 },
      11: { is_blocked: false, neighbor_id: 6 },
      12: { is_blocked: false, neighbor_id: 4 },
    },
  },
  {
    id: 13,
    edges: {
      2: { is_blocked: false, neighbor_id: 16 },
      3: { is_blocked: false, neighbor_id: 16 },
      4: { is_blocked: false, neighbor_id: 11 },
      5: { is_blocked: false, neighbor_id: 11 },
      6: { is_blocked: false, neighbor_id: 8 },
      7: { is_blocked: false, neighbor_id: 8 },
      8: { is_blocked: false, neighbor_id: 10 },
      9: { is_blocked: false, neighbor_id: 10 },
      10: { is_blocked: false, neighbor_id: 15 },
      11: { is_blocked: false, neighbor_id: 15 },
      12: { is_blocked: false, neighbor_id: 18 },
    },
  },
  {
    id: 12,
    edges: {
      2: { is_blocked: false, neighbor_id: 15 },
      3: { is_blocked: false, neighbor_id: 15 },
      4: { is_blocked: false, neighbor_id: 10 },
      5: { is_blocked: false, neighbor_id: 10 },
      6: { is_blocked: false, neighbor_id: 7 },
      7: { is_blocked: false, neighbor_id: 7 },
      8: { is_blocked: false, neighbor_id: 9 },
      9: { is_blocked: false, neighbor_id: 9 },
      10: { is_blocked: false, neighbor_id: 14 },
      11: { is_blocked: false, neighbor_id: 14 },
      12: { is_blocked: false, neighbor_id: 17 },
    },
  },
  {
    id: 11,
    edges: {
      2: { is_blocked: false, neighbor_id: 2 },
      3: { is_blocked: false, neighbor_id: 2 },
      4: { is_blocked: false, neighbor_id: 17 },
      5: { is_blocked: false, neighbor_id: 17 },
      6: { is_blocked: false, neighbor_id: 6 },
      7: { is_blocked: false, neighbor_id: 6 },
      8: { is_blocked: false, neighbor_id: 8 },
      9: { is_blocked: false, neighbor_id: 8 },
      10: { is_blocked: false, neighbor_id: 13 },
      11: { is_blocked: false, neighbor_id: 13 },
      12: { is_blocked: false, neighbor_id: 16 },
    },
  },
  {
    id: 10,
    edges: {
      2: { is_blocked: false, neighbor_id: 13 },
      3: { is_blocked: false, neighbor_id: 13 },
      4: { is_blocked: false, neighbor_id: 8 },
      5: { is_blocked: false, neighbor_id: 8 },
      6: { is_blocked: false, neighbor_id: 5 },
      7: { is_blocked: false, neighbor_id: 5 },
      8: { is_blocked: false, neighbor_id: 7 },
      9: { is_blocked: false, neighbor_id: 7 },
      10: { is_blocked: false, neighbor_id: 12 },
      11: { is_blocked: false, neighbor_id: 12 },
      12: { is_blocked: false, neighbor_id: 15 },
    },
  },
  {
    id: 9,
    edges: {
      2: { is_blocked: false, neighbor_id: 12 },
      3: { is_blocked: false, neighbor_id: 12 },
      4: { is_blocked: false, neighbor_id: 7 },
      5: { is_blocked: false, neighbor_id: 7 },
      6: { is_blocked: false, neighbor_id: 4 },
      7: { is_blocked: false, neighbor_id: 4 },
      8: { is_blocked: false, neighbor_id: 18 },
      9: { is_blocked: false, neighbor_id: 18 },
      10: { is_blocked: false, neighbor_id: 3 },
      11: { is_blocked: false, neighbor_id: 3 },
      12: { is_blocked: false, neighbor_id: 14 },
    },
  },
  {
    id: 8,
    edges: {
      2: { is_blocked: false, neighbor_id: 11 },
      3: { is_blocked: false, neighbor_id: 11 },
      4: { is_blocked: false, neighbor_id: 6 },
      5: { is_blocked: false, neighbor_id: 6 },
      6: { is_blocked: false, neighbor_id: 3 },
      7: { is_blocked: false, neighbor_id: 3 },
      8: { is_blocked: false, neighbor_id: 5 },
      9: { is_blocked: false, neighbor_id: 5 },
      10: { is_blocked: false, neighbor_id: 10 },
      11: { is_blocked: false, neighbor_id: 10 },
      12: { is_blocked: false, neighbor_id: 13 },
    },
  },
  {
    id: 7,
    edges: {
      2: { is_blocked: false, neighbor_id: 10 },
      3: { is_blocked: false, neighbor_id: 10 },
      4: { is_blocked: false, neighbor_id: 5 },
      5: { is_blocked: false, neighbor_id: 5 },
      6: { is_blocked: false, neighbor_id: 2 },
      7: { is_blocked: false, neighbor_id: 2 },
      8: { is_blocked: false, neighbor_id: 4 },
      9: { is_blocked: false, neighbor_id: 4 },
      10: { is_blocked: false, neighbor_id: 9 },
      11: { is_blocked: false, neighbor_id: 9 },
      12: { is_blocked: false, neighbor_id: 12 },
    },
  },
  {
    id: 6,
    edges: {
      2: { is_blocked: false, neighbor_id: 1 },
      3: { is_blocked: false, neighbor_id: 1 },
      4: { is_blocked: false, neighbor_id: 14 },
      5: { is_blocked: false, neighbor_id: 14 },
      6: { is_blocked: false, neighbor_id: 16 },
      7: { is_blocked: false, neighbor_id: 16 },
      8: { is_blocked: false, neighbor_id: 3 },
      9: { is_blocked: false, neighbor_id: 3 },
      10: { is_blocked: false, neighbor_id: 8 },
      11: { is_blocked: false, neighbor_id: 8 },
      12: { is_blocked: false, neighbor_id: 11 },
    },
  },
  {
    id: 5,
    edges: {
      2: { is_blocked: false, neighbor_id: 8 },
      3: { is_blocked: false, neighbor_id: 8 },
      4: { is_blocked: false, neighbor_id: 3 },
      5: { is_blocked: false, neighbor_id: 3 },
      6: { is_blocked: false, neighbor_id: 1 },
      7: { is_blocked: false, neighbor_id: 1 },
      8: { is_blocked: false, neighbor_id: 2 },
      9: { is_blocked: false, neighbor_id: 2 },
      10: { is_blocked: false, neighbor_id: 7 },
      11: { is_blocked: false, neighbor_id: 7 },
      12: { is_blocked: false, neighbor_id: 10 },
    },
  },
  {
    id: 4,
    edges: {
      2: { is_blocked: false, neighbor_id: 7 },
      3: { is_blocked: false, neighbor_id: 7 },
      4: { is_blocked: false, neighbor_id: 2 },
      5: { is_blocked: false, neighbor_id: 2 },
      6: { is_blocked: false, neighbor_id: 14 },
      7: { is_blocked: false, neighbor_id: 14 },
      8: { is_blocked: false, neighbor_id: 16 },
      9: { is_blocked: false, neighbor_id: 16 },
      10: { is_blocked: false, neighbor_id: 1 },
      11: { is_blocked: false, neighbor_id: 1 },
      12: { is_blocked: false, neighbor_id: 9 },
    },
  },
  {
    id: 3,
    edges: {
      2: { is_blocked: false, neighbor_id: 6 },
      3: { is_blocked: false, neighbor_id: 6 },
      4: { is_blocked: false, neighbor_id: 9 },
      5: { is_blocked: false, neighbor_id: 9 },
      6: { is_blocked: false, neighbor_id: 18 },
      7: { is_blocked: false, neighbor_id: 18 },
      8: { is_blocked: false, neighbor_id: 1 },
      9: { is_blocked: false, neighbor_id: 1 },
      10: { is_blocked: false, neighbor_id: 5 },
      11: { is_blocked: false, neighbor_id: 5 },
      12: { is_blocked: false, neighbor_id: 8 },
    },
  },
  {
    id: 2,
    edges: {
      2: { is_blocked: false, neighbor_id: 5 },
      3: { is_blocked: false, neighbor_id: 5 },
      4: { is_blocked: false, neighbor_id: 1 },
      5: { is_blocked: false, neighbor_id: 1 },
      6: { is_blocked: false, neighbor_id: 17 },
      7: { is_blocked: false, neighbor_id: 17 },
      8: { is_blocked: false, neighbor_id: 11 },
      9: { is_blocked: false, neighbor_id: 11 },
      10: { is_blocked: false, neighbor_id: 4 },
      11: { is_blocked: false, neighbor_id: 4 },
      12: { is_blocked: false, neighbor_id: 7 },
    },
  },
  {
    id: 1,
    edges: {
      2: { is_blocked: false, neighbor_id: 3 },
      3: { is_blocked: false, neighbor_id: 3 },
      4: { is_blocked: false, neighbor_id: 4 },
      5: { is_blocked: false, neighbor_id: 4 },
      6: { is_blocked: false, neighbor_id: 19 },
      7: { is_blocked: false, neighbor_id: 19 },
      8: { is_blocked: false, neighbor_id: 6 },
      9: { is_blocked: false, neighbor_id: 6 },
      10: { is_blocked: false, neighbor_id: 2 },
      11: { is_blocked: false, neighbor_id: 2 },
      12: { is_blocked: false, neighbor_id: 5 },
    },
  },
];
